---
title: "Revealed Corruption and Electoral Accountability in Brazil: How Politicians Anticipate Voting Behavior"
author: "Gustavo Diaz"
format: pdf
geometry:
  - bottom=0mm
header-includes:
    - \pagenumbering{gobble}
---

Governments, civil society organizations, and scholars spend considerable resources implementing and evaluating the effect of anti-corruption interventions. However, decades of cumulative evidence suggest that these interventions rarely lead to the removal of corrupt elected offcials from their positions. A recent interpretation of this gap suggests that corrupt politicians often go unpunished because they react to the knowledge of themselves or others being investigated for corruption in unanticipated ways. This dissertation uses data from a long-running anti-corruption program in Brazil to expand on the unintended consequences of anti-corruption interventions that stem from politicians' strategic behavior. The first chapter shows that mayors randomly selected for auditing in the context of this program reduce public spending, particularly in highly visible budget categories, in years close to an election. I argue that this happens because mayors attempt to preserve their reelection chances by signaling fiscal responsibility. The second chapter shows how mayors that are not directly audited, but are in municipalities close to those with mayors exposed as corrupt, tend to seek reelection under different parties more often. As previous accounts of party switching in Brazil suggest, I argue that this occurs because incumbent politicians expect their constituency to react to the news of nearby corruption with increased scrutiny on their own performance in office, which in turn leads them to switch parties in an attempt to secure a better platform for reelection. The question of the effect of exposure to information about nearby corruption opens the door to a broader methodological question of how to capture this type of effect, which is the focus of the third chapter. Research questions in the social sciences usually suggest spillover or interference effects, but rarely provide guidelines on how to model those effects. In fact, theory often suggests many different plausible operationalizations along the same hypothetical pathway. To overcome this difficulty, I propose and illustrate the properties of a model selection approach that uses tools from supervised machine learning to select among alternative operationalizations. As a whole, this dissertation makes two key contributions. First, it shows how politicians' reaction to anti-corruption interventions can stem from an attempt to avoid electoral accountability. Second, by proposing a model selection approach to interference, it expands the applicability of current tools to analyze interference effects to a broader set of research questions.