---
format: pdf
fontsize: 12pt
urlcolor: blue
---
# Research Outputs

Gustavo Diaz  
*Department of Political Science, McMaster University*  
<diazg2@mcmaster.ca>  
\hrule

&nbsp;

## Publications  

<!-- If I start the tenure track I will use the etaremune latex package to make reverse counts -->

Forthcoming. "Data Sources for the Study of Gender and Corruption." In *Handbook on Gender and Corruption in Democracies*, edited by Emily Beaulieu Bacchus and Tiffany Barnes. Edward Elgar Publishing (with [Kelly Senters Piazza](https://www.usafa.edu/facultyprofile/?smid=23816))

2023\. ["Assessing the Validity of Prevalence Estimates in Double List Experiments."](https://doi.org/10.1017/XPS.2023.24) *Journal of Experimental Political Science*

2022\. ["Women Held Back: The Depressing Effect of Institutional and Norms-Based Barriers on Female Representation in Corrupt Contexts."](https://gustavodiaz.org/files/research/gender_corruption.pdf) In [*Norms, Gender and Corruption: Understanding the Nexus*](https://www.e-elgar.com/shop/gbp/norms-gender-and-corruption-9781802205824.html), edited by Ina Kubbe and Ortrun Merkle. Edward Elgar Publishing
(with [Kelly Senters Piazza](https://www.usafa.edu/facultyprofile/?smid=23816))

2020\. ["Light in the Midst of Chaos: COVID-19 and Female Political Representation."](https://doi.org/10.1016/j.worlddev.2020.105125) *World Development* 136: 105125 (with [Kelly Senters Piazza](https://www.usafa.edu/facultyprofile/?smid=23816))

2020\. ["Survey Experiments and the Quest for Valid Interpretation."](https://gustavodiaz.org/files/research/sage_survey_experiments_chapter.pdf) In [*The SAGE Handbook of Research Methods in Political Science and International Relations*](https://us.sagepub.com/en-us/nam/the-sage-handbook-of-research-methods-in-political-science-and-international-relations/book262875), edited by Luigi Curini and Robert Franzese. London: Sage (with [Christopher Grady](https://publish.illinois.edu/cdgrady2/) and [James H. Kuklinski](https://pol.illinois.edu/directory/profile/kuklinsk))

2014\. ["Civic Education and Voter Turnout Under Voluntary Voting."](https://revistapolitica.uchile.cl/index.php/RP/article/view/33099/34813) *Política* 52(1): 61-91 (In Spanish)



## Under review  

["Balancing Precision and Retention in Experimental Design"](https://gustavodiaz.org/files/research/precision_retention.pdf) (with [Erin Rossiter](http://erossiter.com/))  
*Listed under review at American Political Science Review since May 2023*

["Ignoring Female Performance: A Survey Experiment on Policy Implementation in Argentina."](https://gustavodiaz.org/files/research/gender_performance.pdf) (with [Virginia Oliveros](https://virginiaoliveros.com/), [Rebecca Weitz-Shapiro](https://vivo.brown.edu/display/rweitzsh), and [Matthew S. Winters](https://sites.google.com/site/mswinters1/))  
*Listed under review at British Journal of Political Science since May 2023*

## Working Papers  

["Revealing Nearby Corruption Drives Party Switching: Evidence from Local Level Audits in Brazil"](https://gustavodiaz.org/files/research/nearby_corruption.pdf)

["Mayors Alter Spending to Counter the Electoral Consequences of Increased Monitoring: Evidence from Anti-Corruption Audits in Brazil"](https://gustavodiaz.org/files/research/audit_spending.pdf)

["A Model Selection Approach to Geographic Spillovers."](https://gustavodiaz.org/files/research/model_spillovers.pdf)  
*Best poster award. 2019 Latin American Political Methodology Meeting*

