---
format: pdf
fontsize: 12pt
urlcolor: blue
geometry:
  - bottom=0mm
header-includes:
    - \pagenumbering{gobble}
---
## Diversity Statement

Gustavo Diaz  
*Department of Political Science, McMaster University*  
<diazg2@mcmaster.ca>  
\hrule

&nbsp;

```{r, include = FALSE}
field = "applied statistics"
person = "applied statistician"
```


I am a first-generation scholar in three ways. I am part of the first generation in my family to receive a bachelor's degree, part of the first generation seeking postgraduate education opportunities overseas, and the only person in my family pursuing an academic career. The other "part" is an older sibling that tried to convince me to follow their steps and become and economics major. I refused, since I thought it would involve too much math. I chose political science instead, as it seemed to have less math but still enough to meet family expectations. I was wrong. It had as much math, and I hated until I learned halfway through that I could use data to generate knowledge by myself.

My personal experience puts my in a privileged position to foster diversity and inclusion in `r field`. While the job of the `r person` is to act as a conduit between theoretical and applied work, I recognize that the traditional higher education setting prevents individuals from underrepresented backgrounds to participate in that information exchange on equal footing. I believe this is not due to the quality of previous training, but rather because the conventional spaces for cutting-edge knowledge generation and communication are not sufficiently attractive for individuals that do not fit in conventional disciplinary molds.

My initial efforts focused on facilitating out-of-classroom learning opportunities, which I consider essential to break initial entry barriers. At Illinois, I started a methods cheatsheets project in 2018. In this project, volunteer graduate students write a short introduction to the theory, implementation, and current debates surrounding a technique of their expertise. These resources are shared in a repository available for current and future generations.

Currently, I am working on incorporating these principles into my teaching. My course on data analysis for public opinion and policy is designed to give students enough flexibility to connect statistical theory to their own interests and career goals. For example, in response papers they can choose what parts of a research design they would change if they were in charge of replicating a study on a topic of their choosing.

In the future, I aim to translate these ideas into a sustainable and inclusive research program. I believe the laboratory workflow is the template to follow to incorporate the skills and contributions of different backgrounds. This framework creates a space to foster dialogue across backgrounds, learning styles, and career stages, while also providing a safety net to provide early support to those who may otherwise struggle.