---
output: 
    stevetemplates::statement:
    latex_engine: pdflatex
geometry: margin=1in

title: "Research Statement"
author: Gustavo Diaz
affiliation: Department of Political Science, McMaster University
email: "diazg2@mcmaster.ca"

fontfamily: cochineal
fontsize: 11pt
---

```{r setup, include=F}
region = "the Global South"
fields = "design-based causal inference and computational social science"
```

<!-- One short paragraph or sentence to situate my work. Use the beginning of the ddem syllabus-->
My research focuses on the challenges to accountability and representation in `r region`. This is an area where strategic behavior from both citizens and politicians precludes the identification of successful interventions. My current agenda analyzes the unintended electoral consequences of investigating and exposing corruption, as well as the gendered patterns in citizens' evaluation of politicians' performance in office. This agenda also informs a methodological research program on navigating research design tradeoffs in experiments and quasi-experiments. This document outlines my substantive research program on the electoral consequences of corruption. Please refer to my cover letter or [research page](https://gustavodiaz.org/research.html) for a more comprehensive coverage.

The literature in political science and economics on electoral accountability highlights voters' adverse selection problem: They prefer to have good over bad elected officials but they can only infer an incumbent's type through observable outputs of their performance. Therefore, corrupt incumbents have incentives to hide illicit activities and appear good. To fight corruption, governments, civil society organizations, and scholars devote considerable resources to implementing and evaluating anti-corruption interventions that attempt to bridge the information gap between voters and politicians' performance in office. However, the cumulative evidence suggests that these interventions rarely translate into voters sanctioning corrupt incumbents.

A recent explanation for the lack of electoral sanctions is that politicians undertake preemptive behavior to ward off the negative consequences of corruption. For example, previous research shows that political parties avoid nominating legislators investigated for corruption to reelection. On the other side of the coin, research also shows that local level elected officials switch away from parties investigated for corruption after securing reelection. In short, politicians avoid direct association with corruption.

I expand on this research in work funded by the Lemann Center for Brazilian studies at the University of Illinois, using data from a long-running anti-corruption program in Brazil that randomly selects municipalities to audit their use of federal funds, and combining text analysis and machine learning to create the most comprehensive dataset of corruption infractions to date. I make two contributions to the literature.

First, in a working paper, I argue that the main reason why politicians update their behavior in reaction to increased monitoring is because they expect increased scrutiny from their constituents. This contrasts from previous work suggesting that the primary incentive is top-down enforcement. I show that being selected for auditing leads mayors to shift public spending in a attempt to minimize the chances of uncovering irregularities. Mayors selected for auditing spend less and concentrate their spending in fewer areas when they are eligible for reelection and when the audits are announced close to an election year.

In another working paper, I argue that politicians are also responsive to revealed corruption even when they are not directly connected to it. This is because revealed corruption drives politicians in nearby localities to undertake preemptive behavior to ward off a negative reaction from their constituents. I argue that politicians fear being caught in an electoral anti-corruption wave even when there is no evidence of their own wrong-doing. I show that mayors in municipalities exposed to nearby corruption are more likely to seek reelection under a different party, and that they do so in a pattern that suggests an attempt to secure more resources for reelection.

<!-- ## Gendered evaluations of officeholders' performance -->

<!-- In work with Kelly Senters Piazza (US Air Force Academy), we expand this agenda toward the gendered patterns that underlie how voters evaluate politicians' performance in office in light of corruption. In a forthcoming book chapter in *Norms, Gender and Corruption: Understanding the Nexus*, we use my data on corruption infractions at the local level in Brazil to revisit previous findings on the gendered electoral consequences of corruption. Previous work in this topic uses public opinion data and survey experiments to show how revealing corruption increases support for female representation, yet also how female politicians face harsher sanctions for comparable levels of wrongdoing. We argue that these methods of inquiry do not allow us to translate their conclusions to realistic settings, which we overcome by focusing on the aforementioned anti-corruption program in Brazil. We show that revealing corruption increases support for female representation in the form of an increased proportion of female candidates running for mayor, yet this support does not translate into an increased proportion of women winning elections, which we attribute to incumbent mayors' incentives to counter the rise of female challengers. In another chapter forthcoming in the *Handbook on Gender and Corruption in Democracies*, we discuss the challenges and opportunities of using different data sources to study the relationship between gender and corruption, establishing a tradeoff between validity and generalizability. -->

<!-- This program extends to the study of gendered performance evaluations beyond corruption. In a piece in *World Development*, we highlight how exceptional events, such as corruption, conflict, and public health disasters, can promote female political representation by raising questions around the ability of male leadership to handle crises, as well as priming voters about issues around which women are perceived to have policy expertise. Examining public opinion data and recent media coverage around the world, we argue for the presence of both mechanisms in the current global pandemic, implying a potential surge in female political representation, which in turn can help alleviate the gender inequalities exacerbated by the pandemic. -->

<!-- In work under review with Virginia Oliveros (Tulane), Rebecca Weitz-Shapiro (Brown), and Matt Winters (Illinois), we use a survey experiment in Argentina to show gendered differential reactions to policy implementation. The literature in gender and politics identifies a double bind in performance evaluations, which implies that women officeholders are simultaneously perceived as better types and held to a higher standard than their male counterparts. Most of the literature attributes this differential treatment to different expectations of what men and women should do in office. Our experiment highlights a situation where differential treatment exists even in a context of equally low expectations. We find that only men are receive credit for good policy implementation in the context of a food distribution program. We attribute this result to the voters' perception of male politicians as the default category, meaning that the mention of their gender does not provide any additional information on performance evaluation. On the flip side, mentioning the gender of a female politician leads voters to believe that good performance stems from factors beyond the incumbent's control. -->
