---
output: 
    stevetemplates::statement:
    latex_engine: pdflatex
geometry: margin=1in

title: "Teaching Statement"
author: Gustavo Diaz
affiliation: Department of Political Science, McMaster University
email: "diazg2@mcmaster.ca"

fontfamily: cochineal
fontsize: 11pt
---

# Teaching philosophy

```{r setup, include=F}
field = "political science and researh methods"
comparative = "comparative politics"
cp_offer = "comparative politics, accountability and representation, and the politics of the Global South"
methods_short = "research design and quantitative methods"
methods_offer = "quantitative methods,  causal inference, experiments, and computational social science"
source = "website"
```


I approach teaching `r field` as the task of acquiring a new language. Since students come from different paths and have different career goals, I emphasize developing the skill to think and communicate in the language of the social sciences and translate it to different situations. This gives students the flexibility to engage with the course material on their own terms and apply it to their interests. This approach also creates a set of communication rules that everyone is accountable to, which allows individual students to stay on task no matter how much their interests differ from the course content and provides the group with tools to manage instances of discrimination in the classroom and beyond.

When teaching `r comparative`, I highlight how the complexities of multiple causation in understanding patterns of development around the world translate to policy evaluation and everyday political discussion. I accomplish this by encouraging students to draw analogies between the course material and their personal experiences or interests. For example, I encourage students to write news reports applying to course material using any topic or creative media of their choosing.

In teaching `r methods_short`, I highlight the importance of thinking about the statistical properties of a research design before collecting data. I accomplish by teaching research design as a set of steps that can be encoded in statistical programming forward and interrogated to contrast with alternative research design choices.

# Teaching experience

I have experience teaching substantive and methodological courses to diverse audiences and under different formats. At McMaster, I teach an applied research design course on public policy and public opinion. The goal of this course is to give students hands-on experience in designing a quantitative research project in an area relevant to academia, policy, or industry. 

At Tulane, I taught introduction to comparative politics, emphasizing theoretical and methodological considerations at the core of the course, while simultaneously encouraging students to apply this knowledge to recent events in a region or country of their choosing. I also taught an undergrad senior course on the challenges of developing democracies from the perspective of evidence-based policymaking. This course overviews the main challenges in the path to democratic consolidation around the world, the proposed solutions to these challenges, and introduces conceptual tools for credible causal inference in policy evaluation.

# Teaching interests

I am prepared to teach courses on `r cp_offer`. I can also teach methodological courses on `r methods_offer`. You can find copies of current and sample syllabi in my `r source`.