---
format: pdf
fontsize: 12pt
urlcolor: blue
---
## Teaching Statement

Gustavo Diaz  
*Department of Political Science, McMaster University*  
<diazg2@mcmaster.ca>  
\hrule

&nbsp;

### Teaching philosophy

```{r setup, include=F}
field = "quantitative methods"
students = "political science majors"
cp_offer = "comparative politics, accountability and representation, and the politics of the Global South"
methods_offer = "research design, quantitative methods, causal inference, and computational social science"
source = "teaching portfolio"
```

I approach teaching as the task of acquiring a new language. Since students come from different paths and have different career goals, I emphasize developing the skill to think and communicate in the language of the social sciences and translate it to different situations. This gives students the freedom to engage with the course material on their own terms and apply it to their interests. This approach also creates a set of communication rules that allows individual students to stay on task no matter how much their interests differ from the course content and provides the group with tools to manage instances of discrimination in the classroom and beyond.

To accomplish my objective, I design courses with two principles in mind. First, students need flexibility to engage with the course on their own terms and focus on the content they find useful. For example, my introduction to comparative politics course requires students to deliver news reports on political events in a region of their choosing. I encourage the most generous definitions of "political" and "region". This has led to reports that cover general elections in Germany, homelessness in Seattle, and the allocation of Mardi Gras parade routes. I also allow students to deliver the report using any creative media on their choosing. This means students who are not driven by the course content alone can still use the material as an excuse to practice a skill or pursue their interests.

The second principle is accountability, which is necessary to keep everyone on task while allowing flexibility. This means agreeing on an overarching theme that every single course activity must relate to. For example, early on in my data analysis for public opinion and policy course, I introduce the bias-variance tradeoff as a principle to choose among alternative research designs. We then use this principle in flipped classroom laboratory sessions wherein students propose improving the research design of an existing research design. While students are free to propose any modification they deem appropriate, they are also required to document the explicit or implicit costs that would come from their proposal. They must consider, for instance, that a representative sample is more expensive than a convenience sample, or that implementing a block-randomized experiment may require access to variables that cannot be measured easily.

### Teaching experience

I have experience teaching substantive and methodological courses to diverse audiences and under different formats. At McMaster, I teach data analysis for public policy and public opinion, with emphasis on research designs for credible causal inference. The goal of this course is to give students hands-on experience in designing a quantitative research project in an area relevant to academia, policy, or industry.

At Tulane, I taught an undergrad senior course on the challenges of developing democracies from the perspective of evidence-informed policymaking. This course overviews the main challenges in the path to democratic consolidation around the world, the proposed solutions to these challenges, and how governments, researchers, and civil society organizations use data to evaluate these solutions. The previous version focused primarily design-based causal inference. In a future version, I plan to expand toward the application of machine learning and big data.

I also taught introduction to comparative politics, emphasizing theoretical and methodological considerations as the core of the course, while simultaneously encouraging students to apply this knowledge to recent events in a region or country of their choosing. 

In my time at Illinois, I taught statistics and research methods. In the 2020-2021 academic year, I was the graduate methods teaching assistant in our department. My duties involved advising PhD students taking courses in the quantitative methods sequence, as well as mentoring undergraduates enrolled in the senior honors thesis program. I also served as a teaching assistant for Jake Bowers' introduction to data analysis for political science majors. This course focuses on flipped classroom learning, letting students engage with the course material on their own time and using lecture time to work as a group on problem sets and research projects. I have also contributed as a math camp instructor for three consecutive years, introducing statistical programming in R to incoming graduate students in our department. 

I also had experience teaching on the politics of the Global South. I benefited from exposure to different versions of an introductory course to the politics on developing countries. I taught an online version of this course as an independent instructor following Matt Winters' syllabus, which emphasizes theoretical accounts of economic and political development. I also served as a teaching assistant for Avital Livny's version, which emphasizes building social science concepts and tools to understand cross-national variation in economic development, state formation, regime change, and ethnic conflict.

Teaching to these diverse audiences made me aware of the importance of promoting out-of classroom learning experiences. I organized a reading group on computational social science at Illinois that met regularly in the Summer and Fall of 2017. I started a a collaborative project in which graduate students share cheatsheets introducing their fellows to new methodological tools. I have also enjoyed the experience of mentoring an undergraduate research assistant, using the opportunity to help both of us learn text analysis. In the future, I plan to facilitate and institutionalize similar learning experiences in every aspect of my work.

### Teaching interests

I am prepared to teach courses on `r cp_offer`. I can also teach methods courses on `r methods_offer`. You can find copies of current and sample syllabi in my `r source`.