---
format: pdf
fontsize: 12pt
urlcolor: blue
geometry:
  - bottom=0mm
header-includes:
    - \pagenumbering{gobble}
---
## Professional statement

Gustavo Diaz  
*Department of Political Science, McMaster University*  
<diazg2@mcmaster.ca>  
\hrule

&nbsp;

I received my PhD from a Political Science department in the United States that places heavy emphasis on training students in data science and statistical methods. I was recruited for a postdoctoral position in in Advanced Statistical, Causal Inference, and Computational Methodologies at McMaster to focus on fostering a community around the development and application of cutting-edge statistical methods in Canada. 

Part of my postdoc duties involve serving as the methods editorial assistant for the *American Political Science Review*, one of the leading journals in the discipline. My involve assisting editors in assessing the quality and relevance of scholarship applying cutting-edge techniques from data science and statistics, which gives me an opportunity to shape and influence their implementation. I believe the insights gained from this role put me in a unique position to contribute to the strategic vision of professional and leadership program surrounding data science and statistics.

This experience is a reflection of my early career endeavors to spearhead initiatives that make statistics and data science accessible to new audiences. As a PhD student at Illinois, my efforts focused on facilitating out-of-classroom learning opportunities, which I consider essential to break initial entry barriers to the field. At Illinois, I started a quantitative methods cheatsheets project in 2018. In this project, volunteer graduate students write a short introduction to the theory, implementation, and current debates surrounding a technique of their expertise in statistics and data science. These resources are shared in a repository available for current and future generations. The project started with the goal of filling gaps in graduate coursework and quickly shifted to the introduction of new methods. In the same spirit, I also organized a reading group on data science. 


I see a position in a department that plays a key role in unifying data science instruction across campus as the natural progression of my current role, and I am more than eager to assume leadership positions in this regard. I anticipate pursuing fruitful collaborations with departments in the Faculty of Social Sciences, especially the Department of Political Science, which has established itself as the premier destinations for graduate training in statistics and data science applied to the study of politics in Canada.