---
title: "Combining List Experiments and the Network Scale-Up Method to Improve Prevalence Estimates of Sensitive Attitudes and Behaviors"
author:
  - '**Gustavo Diaz**<br><diazg2@mcmaster.ca>' 
  - '**Ines Fynn**<br><ifynn@uc.cl>'
  - '**Verónica Pérez Bentancur**<br><veronica.perez@cienciassociales.edu.uy>'
  - '**Lucía Tiscornia**<br>lucia.tiscornia@ucd.ie'
date: today
date-format: long
---

# Welcome!

Thank you for visiting my poster! You can find more details about the project here.

- [Poster PDF](files/posters/list_nsum.pdf)
- [Slides](https://gustavodiaz.org/slides/list_nsum/maplemeth.html)
- [Pre-analysis plan](https://doi.org/10.17605/OSF.IO/9MCHG)
- Paper [Coming soon!]

Any kind of feedback is welcomed at this stage!

# More about the project

## Methodological contribution

This is part of Gustavo's broader research program on navigating research design tradeoffs in experiments. It's the second project in a series about tradeoffs in list experiments.

The [first paper](files/research/dle_test.pdf) in the series is accepted at JEPS. In other collaborations, I discuss tradeoffs in field and survey experiments in general. [This recent example](files/research/precision_retention.pdf) is currently under review.

The main methodological takeaway from the project is to remind researchers that we can get additional leverage in studies of sensitive attitudes or behaviors in surveys by including and combining estimates from different questioning techniques.

This point was already made in a piece by [Aronow et al (2015)](https://doi.org/10.1093/jssam/smu023). Researchers cite this article to justify the inclusion of direct questions in list experiments, but they tend to forget that you can do more than simply comparing direct question and list experiment estimates side-by-side. 

At a minimum, our contribution should be read as a reminder that people should be combining estimates more often.

## Substantive contribution

This project is part of a broader research agenda trying to understand why criminal organizations remain embedded in contexts where state capacity is high and overall crime is low.

The main explanation is that criminal organizations replace the state there where the state cannot reach. Hence the focus on  *criminal governance* strategies in the literature [(Lessing 2020)](https://doi.org/10.1017/S1537592720001243). 

Our project aims to describe as accurately as possible the extent of criminal governance strategies in the city of Montevideo, Uruguay. This is a case where the state was heavily invested on reducing crime both through increased police presence and social policy reform around the turn of the century. The traditional state capacity explanation would not predict persistent criminal governance strategies in this case, but we still see them to this day.

Our main argument is that a context of high state presence limits criminal governance strategies to economic mechanisms. So, for example, we would see gangs evicting neighbors from their homes or offering jobs, but we would not see them acting as focal points for conflict resolution among individuals as they do in other contexts (we measure this in a different part of the survey).

We chose four negative and four positive activities as sensitive items for the list experiment and network scale-up questions. These came up from interviews with officials and citizens in the field. Our qualitative fieldwork helped us identify realistic criminal governance strategies to focus on, and helped us notice that discussing them is a sensitive issue, which informs our research design [(Pérez Bentancur and Tiscornia 2022)](https://doi.org/10.1177/00491241221082595).


## Miscellaneous

- We block randomized by police designated areas based on crime victimization. We have two blocks, one for higher crime rates and one for lower crime rates. Our experimental estimates adjust for this.

- We followed the advice in the list experiments literature to include a placebo item to control list to avoid artificial inflation in estimates [(e.g. Riambau and Ostwald 2021)](https://doi.org/10.1017/psrm.2020.18). This decision backfired since all of our estimates are close to zero. We have ruled out other potential problems in list experiments by applying the standard battery of validity checks. We are writing a separate paper about how to avoid this problem and recover estimates when placebo statements obscure prevalence rate estimates in list experiments.

