---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Gustavo Diaz

jobtitle: "Department of Political Science, McMaster University"
address: "Kenneth Taylor Hall 527, 1280 Main Street West, Hamilton, Ontario, Canada"
fontawesome: yes
email: diazg2@mcmaster.ca
github: gustavo-diaz
twitter: gusvalo
#osf: "Enter 5 digit osf string here"
# phone: "+1 217 904 0581"
web: gustavodiaz.org
# updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: blue
urlcolor: blue
header-includes:
  - \usepackage{multicol}
  - \usepackage{hyperref}
---

# Positions  
<!-- Positions singular for now -->
<!-- Remember double space for line skip -->

**McMaster University**  
Postdoctoral Fellow, Department of Political Science \hfill 2022-2024

**Tulane University**  
Postdoctoral Fellow, Center for Inter-American Policy and Research \hfill 2021-2022

# Education  

**University of Illinois at Urbana-Champaign**  
PhD in Poltical Science \hfill 2021  
*Committee:* Jake Bowers (chair), Avital Livny, Gisela Sin, Matthew S. Winters

MA in Political Science \hfill 2017  


**Pontificia Universidad Católica de Chile**  
BA in Political Science \hfill 2014


<!-- # Interests -->

<!-- Political Economy, Political Behavior, Accountability, Representation, Developing Countries, Causal Inference, Machine Learning -->

# Publications  

<!-- If I start the tenure track I will use the etaremune latex package to make reverse counts -->

Forthcoming. "Data Sources for the Study of Gender and Corruption." In *Handbook on Gender and Corruption in Democracies*, edited by Emily Beaulieu Bacchus and Tiffany Barnes. Edward Elgar Publishing (with [Kelly Senters Piazza](https://www.usafa.edu/facultyprofile/?smid=23816))

2023\. ["Assessing the Validity of Prevalence Estimates in Double List Experiments."](https://doi.org/10.1017/XPS.2023.24) *Journal of Experimental Political Science*

2022\. ["Women Held Back: The Depressing Effect of Institutional and Norms-Based Barriers on Female Representation in Corrupt Contexts."](https://gustavodiaz.org/files/research/gender_corruption.pdf) In [*Norms, Gender and Corruption: Understanding the Nexus*](https://www.e-elgar.com/shop/gbp/norms-gender-and-corruption-9781802205824.html), edited by Ina Kubbe and Ortrun Merkle. Edward Elgar Publishing
(with [Kelly Senters Piazza](https://www.usafa.edu/facultyprofile/?smid=23816))

2020\. ["Light in the Midst of Chaos: COVID-19 and Female Political Representation."](https://doi.org/10.1016/j.worlddev.2020.105125) *World Development* 136: 105125 (with [Kelly Senters Piazza](https://www.usafa.edu/facultyprofile/?smid=23816))

2020\. ["Survey Experiments and the Quest for Valid Interpretation."](https://gustavodiaz.org/files/research/sage_survey_experiments_chapter.pdf) In [*The SAGE Handbook of Research Methods in Political Science and International Relations*](https://us.sagepub.com/en-us/nam/the-sage-handbook-of-research-methods-in-political-science-and-international-relations/book262875), edited by Luigi Curini and Robert Franzese. London: Sage (with [Christopher Grady](https://publish.illinois.edu/cdgrady2/) and [James H. Kuklinski](https://pol.illinois.edu/directory/profile/kuklinsk))

2014\. ["Civic Education and Voter Turnout Under Voluntary Voting."](https://revistapolitica.uchile.cl/index.php/RP/article/view/33099/34813) *Política* 52(1): 61-91 (In Spanish)



# Under review  

["Balancing Precision and Retention in Experimental Design"](https://gustavodiaz.org/files/research/precision_retention.pdf) (with [Erin Rossiter](http://erossiter.com/))

["Ignoring Female Performance: A Survey Experiment on Policy Implementation in Argentina."](https://gustavodiaz.org/files/research/gender_performance.pdf) (with [Virginia Oliveros](https://virginiaoliveros.com/), [Rebecca Weitz-Shapiro](https://vivo.brown.edu/display/rweitzsh), and [Matthew S. Winters](https://sites.google.com/site/mswinters1/))

# Working Papers  

["Revealing Nearby Corruption Drives Party Switching: Evidence from Local Level Audits in Brazil"](https://gustavodiaz.org/files/research/nearby_corruption.pdf)

["Mayors Alter Spending to Counter the Electoral Consequences of Increased Monitoring: Evidence from Anti-Corruption Audits in Brazil"](https://gustavodiaz.org/files/research/audit_spending.pdf)

["A Model Selection Approach to Geographic Spillovers."](https://gustavodiaz.org/files/research/model_spillovers.pdf) *Best poster award. 2019 Latin American Political Methodology Meeting*



# Teaching  

## McMaster University  

[Research Design for Public Opinion and Public Policy](https://popw23.gustavodiaz.org/). Spring 2024, 2023

## Tulane University  

[Politics of Developing Democracies](https://gustavodiaz.org/files/teaching/ddem_syllabus.pdf). Spring 2022

[Comparative Politics](https://gustavodiaz.org/teaching/cp_intro/syllabus/polc2300_syllabus.pdf). Fall 2021

## University of Illinois at Urbana-Champaign  

### Instructor  

Comparative Politics in Developing Nations (Online). Summer 2019

Mathcamp for Political Scientists. Fall 2017-2019

### Teaching Assistant  

Research Design and Techniques (Graduate). Jake Bowers and James H. Kuklinski. Spring 2021

Quantitative Methods II (Graduate). Jake Bowers. Spring 2021

Quantitative Methods I (Graduate). Brian Gaines. Fall 2020

Quantitative Methods III (Graduate). Wendy K. Tam Cho Fall 2020

Introduction to Quantitative Political Research. Jake Bowers. Fall 2017

Comparative Politics in Developing Nations. Avital Livny. Fall 2016

# Awards & Honors  

2019-2020\. Werner Baer Dissertation Writing Fellowship. Lemann Center for Brazilian Studies,
University of Illinois

2019\. Best Poster Award. Latin American Political Methodology Meeting. Montevideo, Uruguay

2016\. Rita and Leonard Ogren Award for Academic Excellence. Department of Political Science,
University of Illinois

# Conferences & Talks

<!-- Eventually have to make this into a list by year -->

American Political Science Association: 2023, 2022, 2021, 2019

Annual Meeting of the Society for Political Methodology: 2023, 2022, 2021

MapleMeth: 2023

Journal of Public Policy Political Economy of Development Virtual Workshop: 2022

McMaster University, Spark Centre for Social Research Innovation: 2022

Midwest Political Science Association: 2022, 2021, 2018, 2017

Southern Political Science Association: 2022

Latin American Political Methodology Meeting: 2022, 2021, 2020, 2019

Midwest Workshop in Empirical Political Science: 2021

King's College London, Quantitative Political Economy Research Group: 2021

Washington University in St. Louis: 2021

NYU-CESS Annual Experimental Political Science Conference: 2021, 2020

University of Notre Dame: 2020

University of Minnesota Political Methodology Colloquium: 2019

Empirical Implications of Theoretical Models: 2019

St. Louis Area Methods Meeting: 2019

# Additional Training  

2019\. Empirical Implications of Theoretical Models Summer Institute. Emory University

2014\. Summer School on Mixed Methods. Department of Political Science, PUC

# Skills  

**Languages:** Spanish, French, Portuguese

**Software:** R, STATA, QGIS, GeoDa, GitHub, \LaTeX, Markdown

<!-- # Service -->

<!-- **Reviewer:** *American Political Science Review*, *Comparative Political Studies*, *PS: Political Science & Politics*,  *Journal of Elections, Public Opinion & Parties* -->

<!-- **Committee Member:** Comparative Politics Search Committee (University of Illinois at Urbana-Champaign) -->

<!-- **Discussant:** APSA 2020, MPSA 2021, LAPolmeth 2021 -->

<!-- # References -->

<!-- \begin{multicols}{2} -->
<!-- Jake Bowers\\ -->
<!-- Associate Professor\\ -->
<!-- University of Illinois at Urbana-Champaign\\ -->
<!-- \href{mailto:jwbowers@illinois.edu}{jwbowers@illinois.edu} -->

<!-- Avital Livny\\ -->
<!-- Assistant Professor\\ -->
<!-- University of Illinois at Urbana-Champaign\\ -->
<!-- \href{mailto:alivny@illinois.edu}{alivny@illinois.edu} -->

<!-- Gisela Sin\\ -->
<!-- Associate Professor\\ -->
<!-- University of Illinois at Urbana-Champaign\\ -->
<!-- \href{mailto:gsin@illinois.edu}{gsin@illinois.edu} -->

<!-- Matthew S. Winters\\ -->
<!-- Professor\\ -->
<!-- University of Illinois at Urbana-Champaign\\ -->
<!-- \href{mailto:mwinters@illinois.edu}{mwinters@illinois.edu} -->

<!-- \end{multicols} -->

<!-- Alternative section for 3 refs-->
<!-- # References -->

<!-- Jake Bowers   -->
<!-- Associate Professor, University of Illinois at Urbana-Champaign   -->
<!-- \href{mailto:jwbowers@illinois.edu}{jwbowers@illinois.edu} -->

<!-- Gisela Sin   -->
<!-- Associate Professor, University of Illinois at Urbana-Champaign   -->
<!-- \href{mailto:gsin@illinois.edu}{gsin@illinois.edu} -->

<!-- Matthew S. Winters   -->
<!-- Professor, University of Illinois at Urbana-Champaign   -->
<!-- \href{mailto:mwinters@illinois.edu}{mwinters@illinois.edu} -->



