---
# author:
#   - name: Gustavo Diaz
#     affiliation:
#       - name: '**Gustavo Diaz**'
#         department: | 
#                     | *Kenneth Taylor Hall 527*
#                     | *1280 Main Street West*
#                     | *Hamilton, ON Canada*
#         address: '{{< fa envelope >}} `diazg2@mcmaster.ca`'
#         city: '{{< fa globe >}} `gustavodiaz.org`'
#         country: '{{< fa phone >}} +1 217 904 0581'
opening: "Dear Members of the Search Committee,"
format: letter-pdf
fontsize: 12pt
---


```{r setup, include=F}
place = "the ICP"
jobtitle = "an Assistant Professor in Comparative Politics"
# specialty does not appear in methods letter
specialty = "comparative politics and quantitative methods" 
area = "the challenges to accountability, governance, and representation in the Global South from the a political behavior perspective"
tools = "causal inference and computational social science to develop standards to navigate research design tradeoffs in quantitative studies"
courses = "comparative politics, comparative political behavior, democracy and representation, research design, and quantitative methods"
source = "teaching portfolio"
```

<!-- Think about adding a sentence of work with Michelle -->
I write to express my interest in your call for `r jobtitle`. I am a postdoctoral fellow in the Department of Political Science at McMaster University. I specialize in `r specialty`. I received my PhD from the Department of Political Science at the University of Illinois at Urbana-Champaign under the supervision of Jake Bowers, Matt Winters, Gisela Sin, and Avital Livny.

<!-- Edit this paragraph depending on the search focus -->
<!-- Update as reviews progress -->
Substantively, I research `r area`. Methodologically, I use tools from `r tools`. My work is published in outlets including *World Development* and the *Journal of Experimental Political Science*. My work is also under **revise and resubmit** at the *British Journal of Political Science*.

<!-- RESEARCH -->
<!-- Remember to update the status of stuff sent for review -->
<!-- Nearby corruption -->
My primary agenda stems from an original data collection effort in Brazil, combining text analysis and machine learning to construct the most comprehensive dataset of corruption infractions at the local level. This dataset informs several of my ongoing research programs. The first project focuses on the unintended electoral consequences of investigating corruption, with emphasis on how politicians' informational advantage allows them to undertake preemptive behavior to ward off negative reactions from the public. For example, in a piece under review, I show how mayors with reelection incentives decrease public spending in reaction to being randomly selected for an audit of their use of federal funds. This suggests an attempt to minimize the potential irregularities that audits may uncover.

In another solo-authored working paper, I argue that politicians fear being caught in an electoral anti-corruption wave even when there is no evidence of their own wrong-doing. I show that corruption revelation drives mayors in nearby municipalities to switch parties more often in an effort to secure a better platform for reelection. When politicians are not investigated for corruption themselves but still expect increased scrutiny in their performance, this behavior is more cost-effective than working to improve performance in office.

<!-- Gender corruption -->
The second research program focuses on the gendered electoral consequences of investigating corruption. In a book chapter with Kelly Senters Piazza (US Air Force Academy), we use my corruption infractions dataset to show how corruption revelation increases the proportion of female candidates running for mayor, but not their chances of winning elections. We attribute this to incumbents' incentives to counter the rise of female politicians. In another forthcoming book chapter in a separate volume, we discuss the challenges and opportunities of different data sources to study gender and corruption.

This program has evolved toward the gendered evaluations of officeholders' performance in general. In a piece in *World Development*, we discuss how the COVID-19 pandemic has the potential to promote female political representation through increased discontent with the performance of male-led executives and by priming a health policy issue commonly associated with women. In work under **revise and resubmit** at the *British Journal of Political Science* with Virginia Oliveros (Tulane), Rebecca Weitz-Shapiro (Brown), and Matt Winters (Illinois), we use a survey experiment in Argentina to show gendered differential reactions to policy implementation performance.

<!-- Survey experiments and block rand -->
<!-- Last sentence may vary depending on application -->
This research agenda has also led me to produce methodological work to improve our ability to detect hard-to-observe social and political phenomena. I focus on how scholars can navigate research design tradeoffs before data collection. For example, in an article accepted at the *Journal of Experimental Political Science*, I introduce new tools to assess the validity of estimates in double list experiments. This is a variant of the list experiment that promises more precise results but comes with under-explored questionnaire design complications. My expertise in this subject has led collaborations on topics ranging from support to same-sex marriage in Argentina to criminal governance in Uruguay.

<!-- TEACHING -->
My experience as a methodology and area studies postdoc at two separate institutions has given me the opportunity to teach courses in comparative politics and quantitative methods. At McMaster, I teach data analysis for public opinion and public policy. At Tulane, I taught introduction comparative politics and a senior seminar on the challenges of developing democracies from an evidence-based policy perspective. My work as the methods editorial assistant for the *American Political Science Review* also puts me in a unique position to gain exposure to the most current methods in the field, awareness of which I can incorporate into my teaching and mentoring.

As a graduate student at Illinois, I taught an online course on the politics of developing countries as an independent instructor and served as a teaching assistant for its in-person version. I also served as a teaching assistant for quantitative research methods courses at the undergraduate and PhD levels using a flipped classroom approach. These experiences have prepared me to teach to a diverse student body and to adapt to both online and in-person platforms.

<!-- Teaching plans -->
<!-- Remember to switch from teaching portfolio/website accordingly -->
<!-- Also tweak depending on job -->
I am prepared to teach courses on `r courses`. You can find copies of current and sample syllabi in my `r source`. As a first-generation scholar, my teaching philosophy emphasizes building flexible learning environments for students with different backgrounds and career goals.

<!-- CLOSING -->
I believe my expertise makes me an excellent fit at `r place`. Moreover, returning to my alma mater as a professor would be a dream come true. If you have any questions, you can contact me via email or phone.


Sincerely,

<!-- Remember double spaces to lineskip -->
Gustavo Diaz  
Postdoctoral Fellow  
Department of Political Science  
McMaster University
