---
output: stevetemplates::cover_letter
geometry: margin=1in
header-includes:
  - \pagenumbering{gobble}

author: Gustavo Diaz
address: |
    | Kenneth Taylor Hall 527
    | 1280 Main Street West
    | Hamilton, ON Canada
email: "diazg2@mcmaster.ca"
url: "gustavodiaz.org"
phone: +1 217 904 0581
fontsize: 12pt
mainfont: cochineal
monofont: Fira Code

fontawesome: TRUE
date: '`r format(Sys.Date(), "%B %d, %Y")`'
greetings: "Dear Members of the Search Committee,"
---

```{r setup, include=F}

jobtitle = "a Teaching Stream Assistant Professor in Public Policy and International Development in the Global South"
# specialty does not appear in methods letter
specialty = "comparative politics and quantitative methods" 
place = "UTSC"
area = "the political economy of development"
region = "the Global South"
tools = "design-based causal inference and computational social science"
courses = "program evaluation, the politics of development in the Global South, quantitative methods, research design, and data visualization"
```

<!-- Think about adding a sentence of work with Michelle -->
I write to express my interest in your call for `r jobtitle`. I am a postdoctoral fellow in the Department of Political Science at McMaster University. I specialize in `r specialty`. I received my PhD from the Department of Political Science at the University of Illinois at Urbana-Champaign under the supervision of Jake Bowers, Matt Winters, Gisela Sin, and Avital Livny.

<!-- Edit this paragraph depending on the search focus -->
<!-- Update as reviews progress -->
Substantively, I study `r area` with a focus on the challenges to accountability and representation in `r region`. Methodologically, I specialize in `r tools`. 

<!-- TEACHING -->
My experience as a methodology and area studies postdoc at two separate institutions has given me the opportunity to teach courses in comparative politics and quantitative methods. At McMaster, I teach research design for public opinion and policy evaluation. At Tulane, I taught an introductory course in comparative politics and a senior seminar on the challenges of developing democracies from an evidence-informed policy perspective. My work as the methods editorial assistant for the *American Political Science Review* also puts me in a unique position to gain exposure to the most current methods in the field, awareness of which I can incorporate into my teaching and mentoring.

My time at Illinois also gave me extensive teaching experience. I taught an online course on the politics of developing countries as an independent instructor and served as a teaching assistant for its in-person version. I also served as a teaching assistant for quantitative research methods courses at the undergraduate and PhD levels using a flipped classroom approach. These experiences have prepared me to teach to a diverse student body and to adapt to both online and in-person platforms. I am prepared to teach courses on `r courses`.

<!-- Teaching plans -->
<!-- Remember to switch from teaching portfolio/website accordingly -->
<!-- Also tweak depending on job -->
As a first-generation scholar, my teaching philosophy emphasizes building flexible learning environments for students with different backgrounds and career goals. I emphasize developing the skill to think and communicate in the language of the social sciences and translate it to different situations. This gives students the flexibility to engage with the course material on their own terms and apply it to their interests. This approach also creates a set of communication rules that everyone is accountable to, which allows individual students to stay on task no matter how much their interests differ from the course content and provides the group with tools to manage instances of discrimination in the classroom and beyond.

<!-- RESEARCH -->
<!-- Remember to update the status of stuff sent for review -->
<!-- Nearby corruption -->
My primary substantive research agenda relies on an original data collection effort in Brazil, combining text analysis and machine learning to construct the most comprehensive dataset of corruption infractions at the local level. I study the unintended electoral consequences of corruption that stem from politicians' strategic behavior. I argue that corruption revelation drives politicians in nearby municipalities to undertake preemptive behavior to ward off a negative reaction from their constituents.  While previous literature suggests that partisans might react strategically to anticipate sanctions when their political party is linked to corruption, my work shows that this behavior is even more widespread, and that politicians fear being caught in an electoral anti-corruption wave even when there is no evidence of their own wrong-doing. This program has extended toward understanding the gendered consequences of corruption and other aspect of citizen's evaluation of elected officials' performance.

<!-- Survey experiments and block rand -->
I also maintain a methodological agenda on navigating research design tradeoffs in survey and field experiments, focusing on practices to improve statistical precision before data collection. In a *SAGE Handbook* chapter with Christopher Grady (USAID) and Jim Kuklinski (Illinois), we discuss the merits and challenges of increasingly complex survey experimental designs that improve precision at the expense of ecological validity. In a solo-authored piece under **R&R**, I introduce new tools to assess the validity of estimates in double list experiments. This is a variant of the list experiment that promises more precise results but comes with under-explored questionnaire design complications. In a working paper with Jake Bowers (Illinois) and Christopher Grady, we discuss the circumstances under which researchers should prefer biased yet precise estimators to analyze experimental data, including applications to block-randomization and M-estimation. In another paper under review with Erin Rossiter (Notre Dame), we argue how the gains in precision from adopting good practices in experimental designs, such as block randomization or repeated measurement of outcomes, can be offset by explicit or implicit sample loss.

<!-- CLOSING -->
I believe my expertise makes me an excellent fit at `r place`. If you have any questions, you can contact me via email or phone.


Sincerely,

<!-- Remember double spaces to lineskip -->
Gustavo Diaz  
Postdoctoral Fellow  
Department of Political Science  
McMaster University
