---
# author:
#   - name: Gustavo Diaz
#     affiliation:
#       - name: '**Gustavo Diaz**'
#         department: | 
#                     | *Kenneth Taylor Hall 527*
#                     | *1280 Main Street West*
#                     | *Hamilton, ON Canada*
#         address: '{{< fa envelope >}} `diazg2@mcmaster.ca`'
#         city: '{{< fa globe >}} `gustavodiaz.org`'
#         country: '{{< fa phone >}} +1 217 904 0581'
opening: "Dear Members of the Selection Committee,"
format: letter-pdf
fontsize: 12pt
---


```{r setup, include=F}
jobtitle = "an Assistant Professor"
place = "Texas A&M"
tools = "quantitative methodology"
applications = "questions about evidence-informed policy, with primary regional focus on Latin America"
discipline = "social science"
machine = "machine learning and data science"
courses = "econometrics, causal inference in experimens and observational studies, machine learning, and their application to program evaluation and the political economy of development"
source = "website"
```

I write to express my interest in your call for `r jobtitle`. I am a postdoctoral fellow in Advanced Statistical, Causal Inference, and Computational Methodologies in the Department of Political Science at McMaster University. I received my PhD from the Department of Political Science at the University of Illinois at Urbana-Champaign under the supervision of Jake Bowers, Matt Winters, Gisela Sin, and Avital Livny.

My research develops standards to navigate research design tradeoffs in the social sciences, with emphasis on `r tools`. I apply these ideas to `r applications`. My work is published in outlets including *World Development*, the *Journal of Experimental Political Science*, *The SAGE Handbook of Research Methods in Political Science and International Relations*, and is under **revise and resubmit** at the *American Political Science Review* and the *British Journal of Political Science*.

<!-- RESEARCH -->
<!-- Remember to update the status of stuff sent for review -->
<!-- Survey experiments and block rand -->
My research agenda focuses on developing tools that researchers can adopt to improve statistical precision before data collection. This is overlooked in the statistics, econometrics, and political methodology literature in favor of identifying unbiased estimators. Implicitly, this literature assumes that one can improve statistical precision by increasing sample size. This is not feasible in many `r discipline` applications due to resource limitations. Moreover, resource considerations aside, even the least intrusive study has an ethical mandate to identify a research design that maximizes benefits and minimizes harm at the lowest possible cost.

Focusing on experimentation, this agenda follows two strands. First, I examine cases where one can improve statistical precision without sacrificing unbiasedness, which implies unforeseen costs in other dimensions. For example, in work under **R&R** at the *American Political Science Review* with Erin Rossiter (Notre Dame), we show how implementing alternatives to the standard experimental design, such as pre-post outcome measurement or block randomization, may attenuate the expected gains in precision via explicit or implicit sample loss. In a solo-authored piece forthcoming at the *Journal of Experimental Political Science*, I introduce new tools to assess the validity of estimates in double list experiments. This is a variant of the list experiment that promises more precise results but comes with under-explored questionnaire design complications. In work in progress with Inés Fynn (Universidad Católica del Uruguay), Verónica Pérez Bentancur (Universidad de la República), and Lucía Tiscornia (University College Dublin), we show how to combine list experiments with network scale up questions to improve the precision of prevalence rate estimates for sensitive attitudes and behaviors at the cost one additional assumption.

The second strand focuses on cases where one can improve precision by sacrificing unbiasedness deliberately. For example, in work in progress with Jake Bowers (Illinois) and Christopher Grady (USAID), we discuss the circumstances under which researchers should prefer biased yet precise estimators to analyze experimental data, including applications to block-randomization and M-estimation. In a *SAGE Handbook* chapter with Christopher Grady and Jim Kuklinski (Illinois), we discuss the merits and challenges of increasingly complex survey experimental designs that improve precision at the cost of external validity bias.

<!-- POSTDOC WORK-->
<!-- As part of my postdoc, I contribute to three projects under the supervision of Professor Michele Dion. First, I serve as the methods editorial assistant for the *American Political Science Review*, one of the leading journals in the discipline. My involve assisting editors in assessing the quality and relevance of scholarship applying cutting-edge techniques from data science and statistics, which gives me an opportunity to shape and influence their implementation. -->

<!-- Second, I lead the development of a text analysis workflow for a project that seeks to understand gendered patterns in the application and citation of quantitative methods across the social science. I am building a pipeline to collect and pre-process text data from leading journals in anthropology, economics, political science, and sociology since the year 2000 while also reconstructing citation networks across articles. The endline of this project is to leverage this extensive data collection to determine whether scholars write about their peers' use of statistical and data science methods differently depending on their gender. -->

<!-- Third, in a project that also includes Guillem Riambau (Universitat de Barcelona), we use data from the Asian Barometer to understand whether the presence of others during an interview shapes how people respond to face-to-face surveys. I lead the process of harmonizing and documenting the coding of key variables using data spanning 20 years of surveys across 17 countries. This project aims to improve our understanding of how context, culture, and institutions shape measurement error in cross-national surveys. -->

<!-- One paragraph about data/science applications -->
<!-- Needs to be added on research statement too! -->
I plan to expand my research program toward the use of `r machine` to improve statistical inference. An early example comes from my dissertation work, funded by the Lemann Center for Brazilian Studies, on the effect of investigating the use of federal funds among selected mayors in Brazil on the behavior of other mayors in nearby localities.  My theory suggests geographic spillovers as a quantity of interest, yet it gives no guidelines for how far away that effect would travel. This presents a tradeoff between operationalizations that introduce bias by being too narrow or too broad. I overcame this problem using a penalized regression framework to choose the optimal upper bound. This innovation received the best poster award in the 2019 Latin American Political Methodology meeting.

<!-- URUGUAY -->
<!-- I plan to use the insights of my work to inform applications around key questions in political behavior. In turn, I aim to use applications as a motivation for further methodological innovation. For example, in work in progress with with Inés Fynn (Universidad Católica del Uruguay), Verónica Pérez (Universidad de la República), and Lucía Tiscornia (University College Dublin), we apply my work on list experiments to document the extent of negative and positive criminal governance strategies in Uruguay. This project also develops techniques to combine prevalence estimates from list experiments with network scale-up questions, a technique more common in the health sciences. This expands the range of tools available to measure sensitive attitudes and behaviors through surveys. -->


<!-- TEACHING -->
<!-- Remember to tweak based on whether the job is cp friendly -->
My teaching focuses on making quantitative methods accessible to diverse audiences through a combination of flexibility and accountability. I have experience teaching courses on quantitative methods and world politics. At McMaster, I teach data analysis for public policy and public opinion. At Tulane, I taught a seminar on evidence-based policy to address social and political challenges in developing democracies. Both courses emphasize experimental and quasi-experimental designs, and I plan to expand them to include applications to machine learning and data science in the future. At Illinois, I served as a teaching assistant for statistics courses at the undergraduate and PhD levels using a flipped classroom approach. I also served as a math camp instructor for incoming graduate students for three consecutive years. I also have experience teaching introduction to comparative politics in a hybrid format and an online course on the politics of developing countries.

My involvement beyond the classroom also complements my teaching and mentoring. My work as the methods editorial assistant for the *American Political Science Review* gives me the opportunity to shape and influence the development and application of cutting-edge methods in the field. As a PhD student at Illinois, I started a collaborative project in which graduate students introduced their peers to new methods and organized a reading group on computational social science.

<!-- Take this out to fit pages -->
<!-- These experiences have prepared me to teach to a diverse student body, to adapt to both online and in-person platforms, and to teach both the theory and application of quantitative methods. -->

<!-- Teaching plans -->
<!-- Remember to switch from teaching portfolio/website accordingly -->
<!-- Also tweak depending on job -->
<!-- I am prepared to teach courses on `r courses`. You can find copies of current and sample syllabi in my `r source`. -->

<!-- Tailored for Texas A&M -->
I am prepared to teach introductory courses in a research design quantitative methods sequence, as well as electives in causal inference, experiments, survey design, machine learning, data visualization, and their application to evidence-informed policy in the Global South and beyond. You can find copies of current and sample syllabi in my website.

<!-- CLOSING -->
I believe my expertise makes me an excellent fit at `r place`. If you have any questions, you can contact me via email or phone.


Sincerely,

<!-- Remember double spaces to lineskip -->
Gustavo Diaz  
Postdoctoral Fellow  
Department of Political Science  
McMaster University

