---
author:
  - name: Gustavo Diaz
    affiliation:
      - name: '**Gustavo Diaz**'
        department: | 
                    | *Kenneth Taylor Hall 527*
                    | *1280 Main Street West*
                    | *Hamilton, ON Canada*
        address: '{{< fa envelope >}} `diazg2@mcmaster.ca`'
        city: '{{< fa globe >}} `gustavodiaz.org`'
        country: '{{< fa phone >}} +1 217 904 0581'
opening: "Chers membres du comité de recrutement,"
format: letter-pdf
fontsize: 12pt
---

Je vous écris à propos de votre annonce pour un poste de professeur adjoint en sciences des données politiques et sociales. Actuellement, je suis stagiaire postdoctorale en méthodologies statistiques avancées, analyse causale, et sciences des données au département de science politique à l'Université McMaster. J'ai obtenu mon doctorat (*University of Illinois at Urbana-Champaign*) sous la direction de Jake Bowers, Matt Winters, Gisela Sin et Avital Livny.

Je recherche le développement des critères pour naviguer les compromis liés à la conception de recherche en sciences sociales, avec l'accent mis sur les sciences sociales computationnelles et l'analyse causale. J'applique ces idées aux questions de gouvernance et représentation dans le Sud global. Mes travaux sont publiés dans revues et volumes telles que *World Development*, le *Journal of Experimental Political Science* et le *SAGE Handbook of Research Methods in Political Science and International Relations*.

Mon programme de recherche se concentre sur le développement d'outils qu'on peut adopter pour améliorer la précision statistique avant la collecte de données. Cette dimension est souvent négligée dans la littérature en statistiques, en économétrie et en méthodologie politique, au profit de l'identification d'estimateurs non biaisés. Implicitement, cette littérature suppose qu'on peut améliorer la précision en augmentant la taille de l'échantillon. Cela n'est pas possible dans les applications habituelles en science politique en raison de contraintes de ressources. En plus, même l'étude la moins intrusive a un mandat d'identifier une conception de recherche qui maximise les avantages et minimise les préjudices au coût le plus bas.

Cet agenda suit deux lignes de recherche, avec l'accent mis sur les essais contrôlés aléatoires. Premièrement, j'examine comme on peut améliorer la précision statistique sans introduire de biais, ce qui implique des coûts imprévus en autres dimensions. Par exemple, dans un travail en révision avec Erin Rossiter (*Notre Dame*), nous étudions comment des techniques telles que la randomisation par blocs et les *pre-post designs*, initialement conçues pour améliorer la précision, peuvent atténuer les gains de précision en réduisant la taille de l'échantillon. Dans un article du *Journal of Experimental Political Science*, j'introduis nouveaux outils pour évaluer la validité des estimations dans les *double list experiments*. Il s'agit d'une variante du *list experiment* qui promet des résultats plus précis mais présente des complications sous-explorées dans la conception du questionnaire. Dans un travail en cours avec Inés Fynn (*Universidad Católica del Uruguay*), Verónica Pérez Bentancur (*Universidad de la República*) et Lucía Tiscornia (*University College Dublin*), nous combinons le *list experiment* avec des questions du *network scale-up method* pour améliorer la précision des estimations des attitudes sensibles au prix d'un postulat supplémentaire.

Deuxièmement, j'étude les situations dans lesquelles on peut améliorer la précision en introduisant de biais intentionnellement. Par exemple, dans un travail en cours avec Jake Bowers (Illinois) and Christopher Grady (USAID), nous discutons les circonstances dans lesquelles on devraient privilégier des estimateurs biaisés mais précis en l'analyse des données expérimentales, avec applications sur la randomisation par blocs et les M-estimateurs. Dans un *SAGE Handbook* chapitre avec Christopher Grady et Jim Kuklinski (Illinois), nous discutons des mérites et défis des expériences dans enquêtes qui deviennent de plus en plus complexes. Cela se traduit par une amélioration de la précision au prix du biais de validité externe.

Mon expérience d'enseignement comprend des cours sur les méthodes quantitatives et en politique comparée. À McMaster, j'enseigne l'analyse de données pour les politiques publiques et l'opinion publique. À l'université Tulane, j'ai enseigné les politiques basées sur des preuves dans les démocraties en développement. Ces deux cours mettent l'accent sur l'analyse causale, et j'ai l'intention de les élargir pour inclure applications sur l'apprentissage automatique et la science des données. En Illinois, j'ai été auxiliaire d'enseignement en l'analyse des données au niveau du baccalauréat et doctorat avec une modèle de classe inversée. J'ai également enseigné dans le math-camp  pendant trois années consécutives. J'ai aussi l'expérience d'enseigner l'introduction à la politique comparée en format hybride et la politique des pays en développement en ligne.

Ma participation extracurriculaire contribue également à mon enseignement. En tant que assistant éditorial en méthodologie pour l'*American Political Science Review*, j'ai l'opportunité de influencer le développement des méthodes avancés dans la discipline. En tant que doctorant en Illinois, j'ai initié un projet collaboratif dans lequel les doctorants introduit nouvelles méthodes à leurs pairs et j'ai organisé un groupe de lecture sur les sciences sociales computationnelles.

Je suis prêt à enseigner des cours sur la statistique, l'analyse causale, les essais contrôlés aléatoires, les sciences sociales computationnelles, l'apprentissage automatique, ainsi que leur application aux politiques basées sur des preuves. Vous pouvez trouver des exemplaires des programmes dans mon site web.

Je crois que mon expertise me rend bien adapté à l'UdeM. Je ne suis pas citoyen/résident permanent du Canada, mais j'ai l'expérience d'avoir étudié à l'UdeM. Ce qui signifie que je peux m'engager à l'enseignement conformément à la politique linguistique dans les délais impartis. N'hésitez pas à me contacter si vous avez des questions.




Cordialement,

<!-- Remember double spaces to lineskip -->
Gustavo Diaz  
Postdoctoral Fellow  
Department of Political Science  
McMaster University

