---
author:
  - name: Gustavo Diaz
    affiliation:
      - name: '**Gustavo Diaz**'
        department: | 
                    | *Kenneth Taylor Hall 527*
                    | *1280 Main Street West*
                    | *Hamilton, ON Canada*
        address: '{{< fa envelope >}} `diazg2@mcmaster.ca`'
        city: '{{< fa globe >}} `gustavodiaz.org`'
        country: '{{< fa phone >}} +1 217 904 0581'
opening: "Dear Members of the Search Committee,"
format: letter-pdf
fontsize: 12pt
---


```{r setup, include=F}

jobtitle = "an Assistant Professor of Government"
place = "Hamilton College"
tools = "computational social science and design-based causal inference"
applications = "questions around the use of evidence-informed policy to address social and political challenges in democracies"
discipline = "political science"
courses = "quantitative methods, research design, computational social science, and evidence-informed policy"
source = "teaching portfolio"
```

I write to express my interest in your call for `r jobtitle`. I am a postdoctoral fellow in Advanced Statistical, Causal Inference, and Computational Methodologies in the Department of Political Science at McMaster University. I received my PhD from the Department of Political Science at the University of Illinois at Urbana-Champaign under the supervision of Jake Bowers, Matt Winters, Gisela Sin, and Avital Livny.

Is study the application of tools `r tools` to improve research design in the social sciences. I apply these ideas to `r applications`.

<!-- TEACHING -->
<!-- Remember to tweak based on whether the job is cp friendly -->
I have experience teaching courses on quantitative methods and comparative politics. At McMaster, I teach data analysis for public policy and public opinion. At Tulane, I taught a seminar on evidence-informed policy to address social and political challenges in developing democracies. Both courses emphasize experimental and quasi-experimental designs for causal inference. At Illinois, I served as a teaching assistant for statistics courses at the undergraduate and PhD levels using a flipped classroom approach. I also served as a math camp instructor for incoming graduate students for three consecutive years. I also have experience teaching introduction to comparative politics in a hybrid format and an online course on the politics of developing countries. 

My involvement beyond the classroom also complements my teaching and mentoring. My work as the methods editorial assistant for the *American Political Science Review* exposes me to cutting-edge methods in the field. As a PhD student at Illinois, I started a collaborative project in which graduate students introduced their peers to new methods and organized a reading group on computational social science methods. 

These experiences have prepared me to teach to a diverse student body, to adapt to both online and in-person platforms, and to teach both the theory and application of quantitative methods.

<!-- Teaching plans -->
<!-- Remember to switch from teaching portfolio/website accordingly -->
<!-- Also tweak depending on job -->
I am prepared to teach courses on `r courses`. You can find copies of current and sample syllabi in my `r source`. As a first-generation scholar, my teaching philosophy emphasizes using the language of the social sciences as a tool to advance the careers of students with different backgrounds and goals.

<!-- RESEARCH -->
<!-- Remember to update the status of stuff sent for review -->
<!-- Survey experiments and block rand -->
My research agenda focuses on developing tools that researchers can adopt to improve statistical precision before data collection. This is overlooked in the statistics, econometrics, and political methodology literature in favor of identifying unbiased estimators. Implicitly, this literature assumes that one can improve statistical precision by increasing sample size. This is not feasible in many `r discipline` applications due to resource limitations. Moreover, resource considerations aside, even the least intrusive study has an ethical mandate to identify a research design that maximizes benefits and minimizes harm at the lowest possible cost.

Focusing on field and survey experiments, this agenda follows two strands. First, I examine cases where one can improve statistical precision without sacrificing unbiasedness, which implies unforeseen costs in other dimensions. For example, in work under review with Erin Rossiter (Notre Dame), we show how implementing alternatives to the standard experimental design, such as pre-post outcome measurement or block randomization, may attenuate the expected gains in precision via explicit or implicit sample loss. In a solo-authored piece accepted at the *Journal of Experimental Political Science*, I introduce new tools to assess the validity of estimates in double list experiments. This is a variant of the list experiment that promises more precise results but comes with under-explored questionnaire design complications. In work in progress with Inés Fynn (Universidad Católica del Uruguay), Verónica Pérez Bentancur (Universidad de la República), and Lucía Tiscornia (University College Dublin), we show how to combine list experiments with network scale up questions to improve the precision of prevalence rate estimates for sensitive attitudes and behaviors at the cost one additional assumption.

The second strand focuses on cases where one can improve precision by sacrificing unbiasedness deliberately. For example, in work in progress with Jake Bowers (Illinois) and Christopher Grady (USAID), we discuss the circumstances under which researchers should prefer biased yet precise estimators to analyze experimental data, including applications to block-randomization and M-estimation. In a *SAGE Handbook* chapter with Christopher Grady and Jim Kuklinski (Illinois), we discuss the merits and challenges of increasingly complex survey experimental designs that improve precision at the cost of external validity bias.

<!-- CLOSING -->
I believe my expertise makes me an excellent fit at `r place`. If you have any questions, you can contact me via email or phone.


Sincerely,

<!-- Remember double spaces to lineskip -->
Gustavo Diaz  
Postdoctoral Fellow  
Department of Political Science  
McMaster University

